import os

POSTGRES_HOST = os.environ.get('POSTGRES_HOST') #'localhost'
POSTGRES_DATABASE = os.environ.get('POSTGRES_DATABASE') #'fastapi'
POSTGRES_USER = os.environ.get('POSTGRES_USER') #'postgres'
POSTGRES_PASS = os.environ.get('POSTGRES_PASS') #'admin123'
SECRET_KEY  = os.environ.get('SECRET_KEY') #"09c47fdd132bc4c948adf7dac546c2213ab91cbdd572addbfb844aab6167d295"
ALGORITHM = os.environ.get('ALGORITHM') #"HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = os.environ.get('ACCESS_TOKEN_EXPIRE_MINUTES') #30

print("POSTGRES_HOST:",POSTGRES_HOST)
print("POSTGRES_DATABASE:",POSTGRES_DATABASE)
print("POSTGRES_USER:",POSTGRES_USER)
print("POSTGRES_PASS:",POSTGRES_PASS)
print("SECRET_KEY:",SECRET_KEY)
print("ALGORITHM:",ALGORITHM)
print("ACCESS_TOKEN_EXPIRE_MINUTES:",ACCESS_TOKEN_EXPIRE_MINUTES)