name: Build and Deploy Code # name of function

# on: [push,pull_request]

on: # triggers action
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo # description for command
        uses: actions/checkout@v2 # pull changing
      - name: greeting info
        run: echo "hello deployer!"
      - name: install python version 3.9
        uses: actions/setup-python@v2 # use defined action (builtin)
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip # run command on linux
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest -x -d

